version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_PORT: 8010
      POSTGRES_DB: default_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: changeme
    links:
      - "db"
    depends_on:
      - db
    ports:
    - 8010:8010
    healthcheck:
      test: "curl --fail --silent localhost:8010/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  flyway-migrator:
    image: flyway/flyway:6.3.2
    depends_on:
      - db
    volumes:
      - ./migrations/db:/flyway/sql
    command: -url=jdbc:postgresql://${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-default_db} -user=${POSTGRES_USER:-default_user} -password=${POSTGRES_PASSWORD:-changeme} -connectRetries=60 migrate

  db:
    image: postgres:11.5-alpine
    ports:
      - '6667:5432'
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: default_db
      POSTGRES_USER: default_user
    restart: unless-stopped
    volumes:
      - ./pg_db:/var/lib/postgresql/data
      - ./db_scripts/create_db.sql:/docker-entrypoint-initdb.d/01-sessions.sql